# Generated by Django 4.2.2 on 2023-06-11 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='car_price',
            new_name='price',
        ),
    ]
