# Generated by Django 4.2.2 on 2023-06-11 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0002_rename_car_price_vehicle_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='car_type',
            new_name='cartype',
        ),
    ]
