# Generated by Django 4.2.2 on 2023-06-11 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0003_rename_car_type_vehicle_cartype'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('semester', models.IntegerField()),
                ('personal_page', models.URLField()),
            ],
            options={
                'ordering': ['first_name'],
            },
        ),
    ]
