# Generated by Django 4.2.1 on 2023-07-06 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0005_vehicle_air_conditioning_vehicle_airbags_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordervehicle',
            old_name='quantity',
            new_name='vehicles_ordered',
        ),
    ]
